### ISSUE TITLE
Return the Ackee Tracker instance

### ISSUE THREAD

**Issue by suda** [gaia-green-tech/svelte-ackee#3]
When calling `useAckeeSapper` or `useAckeeSvelte` it would be nice to return the underlying `ackeeTracker` instance so it can be used outside of the middleware.

**Comment by sebastian** [comment]
This would be great! I would like this feature in order to be able to track events as well.

**Comment by suda** [comment]
@sebastian Just published `1.3.0` which ships this feature :+1:

**Comment by sebastian** [comment]
That's wonderful, @suda! Thank you!
